server:
  additionalApplications:
    - name: core-applications
      namespace: argocd
      project: default
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      source:
        repoURL: git@github.com:AlexWendland/argocd-test.git
        targetRevision: HEAD
        path: deploy/init-application
        directory:
          recurse: true
      destination:
        namespace: core-applications
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
  extraArgs:
    - --insecure
  config:
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs