apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-test
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: deploy/helm/argo-workflows-test
    repoURL: git@github.com:AlexWendland/argocd-test.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false