apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.0.0"
    helm:
      values: |
        images:
          datasources:
          - name: Loki
            type: loki
            url: http://loki:3100
            access: proxy
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
