# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: loki
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   project: default
#   source:
#     chart: loki-stack
#     repoURL: https://grafana.github.io/helm-charts
#     targetRevision: "2.8.2"
#   destination:
#     namespace: loki
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
